name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/docs.yml'
      - 'jsdoc.config.json'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Generate Documentation
        run: yarn jsdoc -c jsdoc.config.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          commit_message: "docs: update documentation"